### ISSUE TITLE
Further automation

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/bootstrap#6]
There is some obvious automation which could simplify the users' Spine configuration process:
 - [x] apply the default repositories;
 - [x] configure generated resources to be the part of source sets;
 - [x] add shortcuts for client- and server- testing libraries;
 - [x] ~~allow to enable pre-configured PMD and/or Error-Prone checks (see the config in `server-quickstart`);~~
 - [x] explude Protobuf Lite artifacts from `runtimeClasspath` and `testRuntimeClasspath`:
```gradle
configurations {
    // Avoid collisions of Java classes defined both in `protobuf-lite` and `protobuf-java`
    runtime.exclude group: "com.google.protobuf", module: "protobuf-lite"
    testRuntime.exclude group: "com.google.protobuf", module: "protobuf-lite"
}
```
 - [x] configure IDEA directory structure for the user:
```gradle
idea {
    module {
        generatedSourceDirs += file(generatedJavaDir)
        // ...
        testSourceDirs += file(generatedTestJavaDir)
        // ...
    }
}
```
 - [x] ~~enable Google Cloud integration with a single config (add dependencies, apply the Gradle plugin, etc.)~~;
 - [x] add test dependencies when configuring Java projects.

**Comment by alexander-yevsyukov** [comment]
>  add shortcuts for client- and server- testing libraries;

Why cannot we just add required `testImplementation` dependencies if the user enables corresponding production part? 

People who are smart enough to understand the framework would test their code anyway.
Can they test it somehow else but using our testing libraries? I doubt.

@dmdashenkov @armiol what's your take on this?

**Comment by alexander-yevsyukov** [comment]
I do have a only one dependency in the Hello World example:

```gradle
dependencies {
    testImplementation "io.spine:spine-testutil-server:${spine.version()}"
}
```
It feels awkward explaining why we add this dependency, once we added `spine.enableJava().server()` to the Gradle project.

**Comment by dmdashenkov** [comment]
@alexander-yevsyukov, I think, we've already done this item. I'll check and tick it if it's addressed.

**Comment by alexander-yevsyukov** [comment]
Good to know. I tried removed the explicitly defined dependency, and it worked.

**Comment by dmdashenkov** [comment]
@alexander-yevsyukov, exactly as by your comment, we add testutil libraries when the main-scope library is added. For example, if the user enables `server()`, we add a dependency on `spine-server` (via `implementation`) and `spine-testutil-server` (via `testImplementation`).

**Comment by dmdashenkov** [comment]
After giving it a thought, we probably shouldn't configure the Google Cloud plugin for the user as it seems a bit excessive. We might want to allow them adding our `gcloud` libraries to their dependencies.

**Comment by alexander-yevsyukov** [comment]
Discussed the PMD/Checkstyle item with @dmdashenkov and agreed to postpone it until we have more feedback if this is really needed.
